---
all:
  children:
    k3s_cluster:
      children:
        k3s_masters:
          hosts:
            k3s-master-1:
              ansible_host: 192.168.1.101
            k3s-master-2:
              ansible_host: 192.168.1.102
            k3s-master-3:
              ansible_host: 192.168.1.103
        k3s_workers:
          hosts:
            k3s-worker-1:
              ansible_host: 192.168.1.104
            k3s-worker-2:
              ansible_host: 192.168.1.105
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_become: true