---
# Cilium CNI installation

- name: Install Helm (if not installed)
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm
  when: inventory_hostname == groups['k3s_masters'][0]

- name: Add Cilium Helm repository
  shell: |
    helm repo add cilium {{ cilium_chart_repo }}
    helm repo update
  when: inventory_hostname == groups['k3s_masters'][0]

- name: Create Helm values file for Cilium
  template:
    src: cilium-values.yaml.j2
    dest: /tmp/cilium-values.yaml
  when: inventory_hostname == groups['k3s_masters'][0]

- name: Wait for all nodes to be Ready
  shell: |
    kubectl wait --for=condition=Ready nodes --all --timeout=600s
  register: kubectl_wait
  until: kubectl_wait.rc == 0
  retries: 20
  delay: 30
  when: inventory_hostname == groups['k3s_masters'][0]

- name: Install Cilium with Helm
  shell: |
    helm install cilium cilium/cilium \
      --version {{ cilium_chart_version }} \
      --namespace {{ cilium_namespace }} \
      --values /tmp/cilium-values.yaml
  args:
    creates: /tmp/cilium_installed
  register: cilium_install
  when: inventory_hostname == groups['k3s_masters'][0]

- name: Mark Cilium as installed
  file:
    path: /tmp/cilium_installed
    state: touch
    mode: 0644
  when: 
    - inventory_hostname == groups['k3s_masters'][0]
    - cilium_install.changed

- name: Wait for Cilium DaemonSet to be ready
  shell: |
    kubectl -n {{ cilium_namespace }} wait --for=condition=Ready pods -l k8s-app=cilium --timeout=600s
  register: cilium_pods_ready
  until: cilium_pods_ready.rc == 0
  retries: 20
  delay: 30
  when: inventory_hostname == groups['k3s_masters'][0]

- name: Label Cilium nodes (if BGP enabled)
  shell: |
    kubectl label nodes {{ item }} --overwrite cilium.io/bgp-announce-pods=true
  with_items: "{{ groups['k3s_cluster'] }}"
  when: 
    - inventory_hostname == groups['k3s_masters'][0]
    - cilium_enable_bgp | bool

- name: Create IPAM pool for LoadBalancer IPs (if BGP enabled)
  shell: |
    cat << EOF | kubectl apply -f -
    apiVersion: "cilium.io/v2alpha1"
    kind: CiliumLoadBalancerIPPool
    metadata:
      name: "lb-ippool"
    spec:
      cidrs:
      - cidr: "{{ cilium_cluster_pool_ipv4_cidr }}"
    EOF
  when: 
    - inventory_hostname == groups['k3s_masters'][0]
    - cilium_enable_bgp | bool

- name: Get Cilium status
  shell: |
    kubectl -n {{ cilium_namespace }} exec -ti ds/cilium -- cilium status
  register: cilium_status
  when: inventory_hostname == groups['k3s_masters'][0]

- name: Display Cilium status
  debug:
    var: cilium_status.stdout_lines
  when: inventory_hostname == groups['k3s_masters'][0]