---
# Common prerequisites for all nodes

- name: Ensure required packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - apt-transport-https
    - ca-certificates
    - gnupg
    - python3
    - python3-pip

- name: Disable swap
  shell: |
    swapoff -a
    sed -i '/swap/d' /etc/fstab
  changed_when: false

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Configure modules
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      br_netfilter
      overlay
    mode: 0644

- name: Load required modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - br_netfilter
    - overlay

- name: Configure kernel parameters for Kubernetes
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    reload: yes
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.conf.all.forwarding
    - net.ipv6.conf.all.forwarding