---
# Common prerequisites for all nodes - modified to work with limited Python/facts support

- name: Check if K3s already exists
  raw: which k3s || echo "not installed"
  register: k3s_check
  changed_when: false

- name: Install basic packages using raw commands
  raw: apt-get update && apt-get install -y curl apt-transport-https ca-certificates gnupg python3 python3-pip
  when: "'not installed' in k3s_check.stdout"

- name: Disable swap
  raw: swapoff -a && sed -i '/swap/d' /etc/fstab
  changed_when: false

- name: Configure kernel parameters for networking
  raw: |
    echo 1 > /proc/sys/net/ipv4/ip_forward
    echo "br_netfilter" > /etc/modules-load.d/k8s.conf
    echo "overlay" >> /etc/modules-load.d/k8s.conf
    modprobe br_netfilter
    modprobe overlay
    echo "net.bridge.bridge-nf-call-iptables = 1" > /etc/sysctl.d/k8s.conf
    echo "net.bridge.bridge-nf-call-ip6tables = 1" >> /etc/sysctl.d/k8s.conf
    echo "net.ipv4.conf.all.forwarding = 1" >> /etc/sysctl.d/k8s.conf
    echo "net.ipv6.conf.all.forwarding = 1" >> /etc/sysctl.d/k8s.conf
    sysctl --system
  changed_when: false